version: '3.3'
services:
  web:
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /home/ec2-user/docker-mount
        target: /app


  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
       POSTGRES_PASSWORD: test@123

volumes:
  docker_vol:
